// Division politica de Colombia usada para sembrar Departamento/Municipio.
//
// Arauca y sus 4 vecinos directos (Casanare, Boyaca, Norte de Santander,
// Vichada) llevan el listado OFICIAL COMPLETO de sus municipios -- sin
// excepcion, tal como pidio el dueño del proyecto. Se verificaron cruzando
// dos fuentes independientes (codigos DIVIPOLA del DANE + los anexos de
// municipios de Wikipedia, que citan al DANE) antes de cargarlos aqui:
//   - Arauca: 7 municipios
//   - Casanare: 19 municipios
//   - Boyaca: 123 municipios
//   - Norte de Santander: 40 municipios
//   - Vichada: 4 municipios
//
// El resto del pais SI sigue siendo un subconjunto curado (capital + las
// ciudades mas conocidas de cada departamento) y no el listado exhaustivo
// del DANE (1122 municipios en total) -- ampliarlo con el mismo nivel de
// detalle exigiria repetir esa verificacion cruzada para los 27
// departamentos restantes. Si hace falta despues, lo correcto es reemplazar
// esas entradas por la tabla oficial DIVIPOLA, no seguir tecleandolas a mano.
export const DEPARTAMENTOS: { nombre: string; municipios: string[] }[] = [
  // --- Arauca y vecinos directos: listado OFICIAL COMPLETO --------------
  {
    nombre: "Arauca",
    municipios: ["Arauca", "Arauquita", "Cravo Norte", "Fortul", "Puerto Rondón", "Saravena", "Tame"],
  },
  {
    nombre: "Casanare",
    municipios: [
      "Yopal",
      "Aguazul",
      "Chámeza",
      "Hato Corozal",
      "La Salina",
      "Maní",
      "Monterrey",
      "Nunchía",
      "Orocué",
      "Paz de Ariporo",
      "Pore",
      "Recetor",
      "Sabanalarga",
      "Sácama",
      "San Luis de Palenque",
      "Támara",
      "Tauramena",
      "Trinidad",
      "Villanueva",
    ],
  },
  {
    nombre: "Boyacá",
    municipios: [
      "Tunja",
      "Chíquiza",
      "Chivatá",
      "Cómbita",
      "Cucaita",
      "Motavita",
      "Oicatá",
      "Samacá",
      "Siachoque",
      "Sora",
      "Soracá",
      "Sotaquirá",
      "Toca",
      "Tuta",
      "Ventaquemada",
      "Chiscas",
      "El Cocuy",
      "El Espino",
      "Guacamayas",
      "Güicán",
      "Panqueba",
      "Labranzagrande",
      "Pajarito",
      "Paya",
      "Pisba",
      "Berbeo",
      "Campohermoso",
      "Miraflores",
      "Páez",
      "San Eduardo",
      "Zetaquira",
      "Boyacá",
      "Ciénega",
      "Jenesano",
      "Nuevo Colón",
      "Ramiriquí",
      "Rondón",
      "Tibaná",
      "Turmequé",
      "Úmbita",
      "Viracachá",
      "Chinavita",
      "Garagoa",
      "Macanal",
      "Pachavita",
      "San Luis de Gaceno",
      "Santa María",
      "Boavita",
      "Covarachía",
      "La Uvita",
      "San Mateo",
      "Sativanorte",
      "Sativasur",
      "Soatá",
      "Susacón",
      "Tipacoque",
      "Briceño",
      "Buenavista",
      "Caldas",
      "Chiquinquirá",
      "Coper",
      "La Victoria",
      "Maripí",
      "Muzo",
      "Otanche",
      "Pauna",
      "Quípama",
      "Saboyá",
      "San Miguel de Sema",
      "San Pablo de Borbur",
      "Tununguá",
      "Almeida",
      "Chivor",
      "Guateque",
      "Guayatá",
      "La Capilla",
      "Somondoco",
      "Sutatenza",
      "Tenza",
      "Arcabuco",
      "Chitaraque",
      "Gachantivá",
      "Moniquirá",
      "Ráquira",
      "Sáchica",
      "San José de Pare",
      "Santa Sofía",
      "Santana",
      "Sutamarchán",
      "Tinjacá",
      "Togüí",
      "Villa de Leyva",
      "Aquitania",
      "Cuítiva",
      "Firavitoba",
      "Gámeza",
      "Iza",
      "Mongua",
      "Monguí",
      "Nobsa",
      "Pesca",
      "Sogamoso",
      "Tibasosa",
      "Tópaga",
      "Tota",
      "Belén",
      "Busbanzá",
      "Cerinza",
      "Corrales",
      "Duitama",
      "Floresta",
      "Paipa",
      "Santa Rosa de Viterbo",
      "Tutazá",
      "Betéitiva",
      "Chita",
      "Jericó",
      "Paz de Río",
      "Socha",
      "Socotá",
      "Tasco",
      "Cubará",
      "Puerto Boyacá",
    ],
  },
  {
    nombre: "Norte de Santander",
    municipios: [
      "Cúcuta",
      "Ábrego",
      "Arboledas",
      "Bochalema",
      "Bucarasica",
      "Cáchira",
      "Cácota",
      "Chinácota",
      "Chitagá",
      "Convención",
      "Cucutilla",
      "Durania",
      "El Carmen",
      "El Tarra",
      "El Zulia",
      "Gramalote",
      "Hacarí",
      "Herrán",
      "La Esperanza",
      "La Playa de Belén",
      "Labateca",
      "Los Patios",
      "Lourdes",
      "Mutiscua",
      "Ocaña",
      "Pamplona",
      "Pamplonita",
      "Puerto Santander",
      "Ragonvalia",
      "Salazar de Las Palmas",
      "San Calixto",
      "San Cayetano",
      "Santiago",
      "Santo Domingo de Silos",
      "Sardinata",
      "Teorama",
      "Tibú",
      "Toledo",
      "Villa Caro",
      "Villa del Rosario",
    ],
  },
  {
    nombre: "Vichada",
    municipios: ["Puerto Carreño", "Cumaribo", "La Primavera", "Santa Rosalía"],
  },

  // --- Bogotá y Cundinamarca: alto volumen de origen de clientes --------
  { nombre: "Bogotá D.C.", municipios: ["Bogotá D.C."] },
  {
    nombre: "Cundinamarca",
    municipios: ["Soacha", "Fusagasugá", "Zipaquirá", "Chía", "Facatativá", "Girardot", "Mosquera", "Madrid"],
  },

  // --- Resto del pais: capital + ciudades mas conocidas ------------------
  { nombre: "Amazonas", municipios: ["Leticia", "Puerto Nariño"] },
  {
    nombre: "Antioquia",
    municipios: ["Medellín", "Bello", "Envigado", "Itagüí", "Rionegro", "Turbo", "Apartadó"],
  },
  { nombre: "Atlántico", municipios: ["Barranquilla", "Soledad", "Malambo", "Sabanalarga"] },
  { nombre: "Bolívar", municipios: ["Cartagena de Indias", "Magangué", "Turbaco"] },
  { nombre: "Caldas", municipios: ["Manizales", "Chinchiná", "La Dorada"] },
  { nombre: "Caquetá", municipios: ["Florencia"] },
  { nombre: "Cauca", municipios: ["Popayán", "Santander de Quilichao"] },
  { nombre: "Cesar", municipios: ["Valledupar", "Aguachica"] },
  { nombre: "Chocó", municipios: ["Quibdó", "Istmina"] },
  { nombre: "Córdoba", municipios: ["Montería", "Cereté", "Sahagún", "Lorica"] },
  { nombre: "Guainía", municipios: ["Inírida"] },
  { nombre: "Guaviare", municipios: ["San José del Guaviare"] },
  { nombre: "Huila", municipios: ["Neiva", "Pitalito", "Garzón"] },
  { nombre: "La Guajira", municipios: ["Riohacha", "Maicao", "Uribia"] },
  { nombre: "Magdalena", municipios: ["Santa Marta", "Ciénaga", "Fundación"] },
  { nombre: "Meta", municipios: ["Villavicencio", "Acacías", "Granada"] },
  { nombre: "Nariño", municipios: ["Pasto", "Ipiales", "Tumaco"] },
  { nombre: "Putumayo", municipios: ["Mocoa", "Puerto Asís"] },
  { nombre: "Quindío", municipios: ["Armenia", "Calarcá"] },
  { nombre: "Risaralda", municipios: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal"] },
  { nombre: "San Andrés y Providencia", municipios: ["San Andrés", "Providencia"] },
  {
    nombre: "Santander",
    municipios: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"],
  },
  { nombre: "Sucre", municipios: ["Sincelejo", "Corozal"] },
  { nombre: "Tolima", municipios: ["Ibagué", "Espinal", "Melgar"] },
  {
    nombre: "Valle del Cauca",
    municipios: ["Cali", "Palmira", "Buenaventura", "Tuluá", "Buga", "Cartago", "Jamundí"],
  },
  { nombre: "Vaupés", municipios: ["Mitú"] },
];
